# Generated by Django 5.1.3 on 2026-07-02 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apk_builds_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_used_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('plus', 'Plus')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_projects_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('plus', 'Plus')], max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bkash_transaction_id', models.CharField(max_length=100)),
                ('bkash_sender_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
