# Generated by Django 5.1.3 on 2026-07-02 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('planning', 'Planning'), ('executing', 'Executing'), ('testing', 'Testing'), ('deploying', 'Deploying'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='created', max_length=20)),
                ('primary_language', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_framework', models.CharField(blank=True, max_length=50, null=True)),
                ('workspace_container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('workspace_volume_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_state', models.JSONField(blank=True, default=dict)),
                ('roadmap', models.JSONField(blank=True, default=dict)),
                ('deployment_url', models.URLField(blank=True, null=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('orchestrator', 'Orchestrator'), ('planner', 'Planner'), ('reader', 'Reader'), ('writer', 'Writer'), ('reviewer', 'Reviewer'), ('tester', 'Tester'), ('debugger', 'Debugger'), ('deployer', 'Deployer'), ('documenter', 'Documenter')], max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('thinking', 'Thinking'), ('plan', 'Plan'), ('action', 'Action'), ('code', 'Code'), ('output', 'Output'), ('error', 'Error'), ('fix', 'Fix'), ('success', 'Success'), ('deployment', 'Deployment'), ('message', 'Message')], default='message', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('api_key_used', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('read', 'Read')], max_length=10)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('plan', 'Plan'), ('read_code', 'Read Code'), ('write_code', 'Write Code'), ('review', 'Review'), ('test', 'Test'), ('debug', 'Debug'), ('deploy', 'Deploy'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('assigned_agent', models.CharField(blank=True, max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='projects.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_label', models.CharField(max_length=20)),
                ('tokens_used', models.IntegerField()),
                ('request_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
    ]
